eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: spring-boot-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ashish-panicker/spring-config-server-repo
          default-label: main
